name = "Example Project"
author = "My Team"
prefix = "exm"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "LICENSE",
]

[version]
git_hash = 0

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
